# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
LABEL io.openshift-expose-services="8080-http" \
      io.openshift.tags="apache, httpd" \
      io.k8s.display-name="custom httpd application"




EXPOSE 8080
RUN sed -i "s/#ServerName www.example.com:80/servername 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf && \
    sed -i "s/Listen 80/Listen 8080/g"  /etc/httpd/conf/httpd.conf
RUN chgrp -R 0 /var/logs/httpd /var/run/httpd && \
    chmod -R g=u  /var/logs/httpd /var/run/httpd

USER 1000

